config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :reservations do
    resources :scores
  end
  devise_for :users
  resources :membership_applications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'membership_applications#new'
end

app/models/membership_application.rb
class MembershipApplication < ApplicationRecord
  belongs_to :user

  canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]\z/
  canadian_phone = /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/

  validates_uniqueness_of :user_id
  validates :address, presence: true
  validates :postal_code, presence: true, format: { with: canadian_postal_code }
  validates :phone, presence: true, format: { with: canadian_phone }
  validates :date_of_birth, presence: true
  validate :at_least_18
  validates :occupation, presence: true
  validates :company_name, presence: true
  validates :company_address, presence: true
  validates :company_postal_code, presence: true, format: { with: canadian_postal_code }
  validates :company_phone, presence: true
  validates :membership, presence: true
  validates :first_sponsor_name, presence: true
  validates :second_sponsor_name, presence: true
  validate :different_sponsors

  private

  def at_least_18
    if self.date_of_birth
      errors.add(:date_of_birth, 'must show that you are 18 years or older (< 1999).') if self.date_of_birth > 18.years.ago.to_date
    end
  end

  def different_sponsors
    errors.add(:first_sponsor_name, "can't be used twice!") unless
    first_sponsor_name != second_sponsor_name
  end
end

app/controllers/membership_applications_controller.rb
class MembershipApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_membership_application, only: [:show, :edit, :update, :destroy]

  # GET /membership_applications
  # GET /membership_applications.json
  def index
    @membership_applications = MembershipApplication.all
  end

  # GET /membership_applications/1
  # GET /membership_applications/1.json
  def show
  end

  # GET /membership_applications/new
  def new
    if current_user.guest == true
      @membership_application = MembershipApplication.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /membership_applications/1/edit
  def edit
  end

  # POST /membership_applications
  # POST /membership_applications.json
  def create
    @user = current_user
    @membership_application = @user.build_membership_application(membership_application_params)
    @user.update_attribute(:guest, false)
    @user.update_attribute(:member, true)

    if @membership_application.membership == "Gold"
      @user.update_attribute(:shareholder, true)
    end

    respond_to do |format|
      if @membership_application.save
        format.html { redirect_to @membership_application, notice: 'Membership application was successfully created.' }
        format.json { render :show, status: :created, location: @membership_application }
      else
        format.html { render :new }
        format.json { render json: @membership_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membership_applications/1
  # PATCH/PUT /membership_applications/1.json
  def update
    respond_to do |format|
      if @membership_application.update(membership_application_params)
        format.html { redirect_to @membership_application, notice: 'Membership application was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership_application }
      else
        format.html { render :edit }
        format.json { render json: @membership_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membership_applications/1
  # DELETE /membership_applications/1.json
  def destroy
    @membership_application.destroy
    respond_to do |format|
      format.html { redirect_to membership_applications_url, notice: 'Membership application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership_application
      @membership_application = MembershipApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_application_params
      params.require(:membership_application).permit(:address, :postal_code, :phone, :occupation, :company_name, :company_address, :company_postal_code, :company_phone, :membership, :first_sponsor_name, :second_sponsor_name, :user_id, :date_of_birth)
    end
end

app/helpers/membership_applications_helper.rb
module MembershipApplicationsHelper
end

app/views/membership_applications/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-md-10 col-md-offset-1">
    <div>
      <%= bootstrap_form_for(@membership_application) do |f| %>
        <% if @membership_application.errors.any? %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            The form contains <%= pluralize(@membership_application.errors.count, "error") %>.
            <ul>
              <% @membership_application.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.text_field :address, autofocus: true, hide_label: true, placeholder: "Address", class: 'form-control' %>
        <%= f.text_field :postal_code, hide_label: true, placeholder: "Postal Code", class: 'form-control' %>
        <%= f.text_field :phone, hide_label: true, placeholder: "Phone", class: 'form-control' %>
        <%= f.date_field :date_of_birth, class: 'form-control' %>
        <%= f.text_field :occupation, hide_label: true, placeholder: "Occupation", class: 'form-control' %>
        <%= f.text_field :company_name, hide_label: true, placeholder: "Company Name", class: 'form-control' %>
        <%= f.text_field :company_address, hide_label: true, placeholder: "Company Address", class: 'form-control' %>
        <%= f.text_field :company_postal_code, hide_label: true, placeholder: "Company Postal Code", class: 'form-control' %>
        <%= f.text_field :company_phone, hide_label: true, placeholder: "Company Phone", class: 'form-control' %>
        <%= f.select :membership, [["Gold", "Gold"], ["Silver", "Silver"], ["Bronze", "Bronze"], ["Copper", "Copper"]], { class: 'form-control' } %>
        <%= f.collection_select(:first_sponsor_name, User.where(shareholder: true), :full_name, :full_name, { class: 'dropdown-menu' }) %>
        <%= f.collection_select(:second_sponsor_name, User.where(shareholder: true), :full_name, :full_name, { class: 'dropdown-menu' }) %>
        <%= f.submit "Submit", class: 'btn btn-lg btn-block btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/membership_applications/edit.html.erb
<h1>Editing Membership Application</h1>

<%= render 'form', membership_application: @membership_application %>

<%= link_to 'Show', @membership_application %> |

app/views/membership_applications/index.html.erb
<div class="col-sm-6 col-md-6 col-md-offset-3">
  <h2>Your Membership</h2>
  <br>
  <% if current_user.nil? %>
    <div>
      <%= link_to 'New Membership application', new_membership_application_path, class: 'btn btn-default btnn-sm pull-right' %>
    </div>
  <% end %>

  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>Applicant</th>
        <th>Membership</th>
        <th>Sponsor 1</th>
        <th>Sponsor 2</th>
        <th class="text-centerActions"</th>
      </tr>
    </thead>
    <tbody>
      <% @membership_applications.each do |membership_application| %>
        <tr>
          <td><%= membership_application.user.full_name %></td>
          <td><%= membership_application.membership %><std>
            <td><%= membership_application.first_sponsor_name %></td>
            <td><%= membership_application.second_sponsor_name %></td>
            <td><%= link_to 'Show', membership_application, class: 'btn btn-info btn-simple btn-xs' %></td>
            <td><%= link_to 'Edit', edit_membership_application_path(membership_application), class: 'btn btn-warning btn-simple btn-xs' %></td>
            <td><%= link_to 'Destroy', membership_application, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-simple btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/membership_applications/new.html.erb
<div class="row">
  <div class="col-sm-8 col-md-7 col-md-offset-3">
    <h2>Membership Application</h2>
  </div>
</div>
<%= render 'form', membership_application: @membership_application %>

app/views/membership_applications/show.html.erb
<p>
  <strong>Applicant:</strong>
  <%= @membership_application.user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @membership_application.user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @membership_application.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @membership_application.postal_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @membership_application.phone %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @membership_application.date_of_birth.strftime("%b %d, %Y") %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @membership_application.occupation %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @membership_application.company_name %>
</p>

<p>
  <strong>Company adress:</strong>
  <%= @membership_application.company_address %>
</p>

<p>
  <strong>Company postal code:</strong>
  <%= @membership_application.company_postal_code %>
</p>

<p>
  <strong>Company phone:</strong>
  <%= @membership_application.company_phone %>
</p>

<p>
  <strong>Membership Type:</strong>
  <%= @membership_application.membership %>
</p>

<p>
  <strong>Sponsor #1:</strong>
  <%= @membership_application.first_sponsor_name %>
</p>

<p>
  <strong>Sponsor #2:</strong>
  <%= @membership_application.second_sponsor_name %>
</p>

<% if current_user.admin == true %>
  <div>
  <%= link_to 'Edit', edit_membership_application_path(@membership_application), class: 'btn btn-sm btn-warning' %> |
  <%= link_to 'Back', membership_applications_path, class: 'btn btn-sm btn-default' %>
  </div>
<% end %>

<style type="text/css" media="screen">
  p {
    line-height: 15%;
  }
</style>