config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :reservations do
    resources :scores
  end
  devise_for :users
  resources :membership_applications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'membership_applications#new'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_one :score

  validates :first_guest_name, presence: true
  validates :carts, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 5 }
  validates :date_and_time, presence: true, uniqueness: true
  validate :date_cannot_be_in_the_past
  validate :first_and_second_names
  validate :first_and_third_names
  validate :second_and_third_names
  validate :first_name_not_current_user
  validate :second_name_not_current_user
  validate :third_name_not_current_user

  private

  def date_cannot_be_in_the_past
    if date_and_time.present? && date_and_time < Date.today
      errors.add(:date_and_time, "can't be in the past")
    end
  end

  def first_and_second_names
    errors.add(:first_guest_name, "can't be used twice!") unless
      first_guest_name != second_guest_name
  end

  def first_and_third_names
    errors.add(:first_guest_name, "can't be used twice!") unless
      first_guest_name != third_guest_name
  end

  def second_and_third_names
    errors.add(:second_guest_name, "can't be used twice!") unless
      second_guest_name != third_guest_name or second_guest_name != nil
  end

  def first_name_not_current_user
    errors.add(:first_guest_name, "can't be you!!") unless
    first_guest_name != user.full_name
  end

  def second_name_not_current_user
    errors.add(:second_guest_name, "can't be you!!") unless
    second_guest_name != user.full_name
  end

  def third_name_not_current_user
    errors.add(:third_guest_name, "can't be you!!") unless
    third_guest_name != user.full_name
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @user = current_user
    @reservation = @user.reservations.build(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:first_guest_name, :second_guest_name, :third_guest_name, :carts, :date_and_time)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-md-6 col-md-offset-3">
    <div>

      <%= bootstrap_form_for(reservation) do |f| %>
        <% if reservation.errors.any? %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            The form contains <%= pluralize(reservation.errors.count, "error") %>.

            <ul>
              <% reservation.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.text_field :first_guest_name, autofocus: true, hide_label: true, placeholder: "First Guest", class: 'form-control' %>
        <%= f.text_field :second_guest_name, hide_label: true, placeholder: "Second Guest", class: 'form-control' %>
        <%= f.text_field :third_guest_name, hide_label: true, placeholder: "Third Guest", class: 'form-control' %>
        <%= f.number_field :carts, hide_label: true, placeholder: "Number of Carts", class: 'form-control' %>
        <%= f.datetime_field :date_and_time, start_year: Time.current.year, end_year: Time.current.year + 10, class: 'form-control' %>

        <%= f.submit "Submit", class: 'btn btn-lg btn-block btn-info' %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<h2 class="text-center">Edit Reservation</h2>

<%= render 'form', reservation: @reservation %>
<div>
  <%= link_to 'Show', @reservation, class: 'btn btn-sm btn-info' %> |
  <%= link_to 'Back', reservations_path, class: 'btn btn-sm btn-default' %>
</div>

app/views/reservations/index.html.erb
<br />

<h2 class="text-center">Your Reservations</h2>
<% if current_user.member == true %>
  <%= link_to 'New Reservation', new_reservation_path, class: 'btn btn-sm btn-default pull-right' %>
<% end %>

<br /> <br /> <br />

<div class="row">
  <% counter = 1 %>
  <% @reservations.each do |reservation| %>
    <div class="col-sm-6">
      <div class="panel panel-success">
        <div class="panel-body">
          <h3 class="text-center">Reservation #<%= counter %></h3>
          <div class="text-center">
            <%= reservation.date_and_time.strftime("%b %d, %Y at %I:%M %p") %>
            <%= link_to 'Show', reservation, class: 'btn btn-sm btn-info' %> | <%= link_to 'Edit', edit_reservation_path(reservation), class: 'btn btn-sm btn-warning' %>
          </div>
          <% if reservation.score != nil %>

          <div class="text-center">
            <%= render reservation.score %>
          </div>
          <% else %>
            <div class="col-sm-8 col-md-9 col-md-offset-2">
              Add Score
            <%= bootstrap_form_for([reservation, reservation.build_score]) do |f| %>
              <% if session[:errors] %>
                <div class="alert alert-danger">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  Ooops! Please correct the following:
                  <ul>
                    <% session[:errors].each do |msg| %>
                      <li class="error"><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
                <% session[:errors] = nil %>
              <% end %>
              <div class="row">
                <div class="col-sm-4">
                  <%= f.number_field :total, class: 'form-control' %>
                </div>
                <div class="col-sm-4">
                  <%= f.number_field :course_rating, class: 'form-control' %>
                </div>
                <div class="col-sm-4">
                  <%= submit_tag "Add", class: 'btn btn-sm btn-block btn-primary' %>
                </div>
              <div>
              <% end %>
              </div>
          <% end %>
          <% counter += 1 %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="row">
  <div class="col-sm-8 col-md-6 col-md-offset-3">
    <h1 class="text-center">New Reservation</h1>
  </div>
</div>

<%= render 'form', reservation: @reservation %>

<div class="row">
  <div class="col-sm-8 col-md-6 col-md-offset-3">
    <%= link_to 'Back', reservations_path %>
  </div>
</div>

app/views/reservations/show.html.erb
<p>
  <strong>Reservee:</strong>
  <%= @reservation.user.full_name %>
</p>

<p>
  <strong>First guest name:</strong>
  <%= @reservation.first_guest_name %>
</p>

<p>
  <strong>Second guest name:</strong>
  <%= @reservation.second_guest_name %>
</p>

<p>
  <strong>Third guest name:</strong>
  <%= @reservation.third_guest_name %>
</p>

<p>
  <strong>Carts:</strong>
  <%= @reservation.carts %>
</p>

<p>
  <strong>Date and Time:</strong>
  <%= @reservation.date_and_time.strftime("%b %d, %Y at %I:%M %p") %>
</p>
<div>
  <%= link_to 'Edit', edit_reservation_path(@reservation), class: 'btn btn-sm btn-warning' %> |
  <%= link_to 'Back', reservations_path, class: 'btn btn-sm btn-default' %>
</div>